export const icons = {
    hamburger: '/images/icons/hamburger.svg',
    x: '/images/icons/x.svg',
    githubColor: '/images/icons/github-color.svg',
    github: '/images/icons/github.svg',
    email: '/images/icons/email.svg',
    twitterColor: '/images/icons/twitter-color.svg',
    twitter: '/images/icons/twitter.svg',
    instagramColor: '/images/icons/instagram-color.svg',
    instagram: '/images/icons/instagram.svg',
    youtube: '/images/icons/youtube.svg',
    linkedinColor: '/images/icons/linkedin-color.svg',
    linkedin: '/images/icons/linkedin.svg',
    spotifyColor: '/images/icons/spotify-color.svg',
    spotify: '/images/icons/spotify.svg',
    bandcamp: '/images/icons/bandcamp.svg',
    download: '/images/icons/download.svg',
    gallery: '/images/icons/gallery.svg',
    website: '/images/icons/website.svg',
    blog: '/images/icons/blog.svg',
    arrowVertical: '/images/icons/arrow-vertical.svg',
    arrowHorizontal: '/images/icons/arrow-horizontal.svg',
    arrowHorizontalShort: '/images/icons/arrow-horizontal-short.svg'
}