import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

function Contact()
{
    return (
        <div className={styles.container}>
    <Head>
        <title>Justin Majetich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
        <a href="/"><h1 className={styles.title}>
        Justin Majetich
        </h1></a>

        <h2>Contact</h2>

        <p className={styles.description}>
        Let's be in touch!
        </p>

        <div className="contacts">
            <p>Email: <a href="mailto:justinmajetich@gmail.com">justinmajetich@gmail.com</a></p>
            <p>LinkedIn: <a href="https://www.linkedin.com/in/justin-majetich/">/in/justinmajetich</a></p>
            <p>Twitter: <a href="https://twitter.com/JustinMajetich">@justinmajetich</a></p>
            <p>GitHub: <a href="https://github.com/justinmajetich">@justinmajetich</a></p>


        </div>

        <div className="nav-bar">
            <Link href="/"><a><h3>Home</h3></a></Link>
            <Link href="/about"><a><h3>About Me</h3></a></Link>
            <Link href="/portfolio"><a><h3>Portfolio</h3></a></Link>
            <Link href="/resume"><a><h3>Resume</h3></a></Link>
        </div>

    </main>

    <footer className={styles.footer}>
        <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
        >
        Powered by{' '}
        <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
        </a>
    </footer>
    </div>
)
}

export default Contact