import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Justin Majetich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Justin Majetich
        </h1>

        <p className={styles.description}>
          Software Engineer | Unity Developer
        </p>

        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
            <h2>About Me &rarr;</h2>
            <p>I'm a Software Engineer with a passion for storytelling.</p>
          </a>

          <a href="/portfolio" className={styles.card}>
            <h2>Portfolio &rarr;</h2>
            <p>Learn about some of my favorite projects!</p>
          </a>

          <a
            href="/resume"
            className={styles.card}
          >
            <h2>Resume &rarr;</h2>
            <p>From Musician to Software Engineer - here's my journey.</p>
          </a>

          <a
            href="/contact"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>
              Feel free to reach out with any work opportunities or just to say hi!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
