import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

function Portfolio()
{
    return (
        <div className={styles.container}>
    <Head>
        <title>Justin Majetich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
        <a href="/"><h1 className={styles.title}>
        Justin Majetich
        </h1></a>

        <h2>Portfolio</h2>

        <div className="project-container">
            <div className="project">
                <h2>VR wheelchair</h2>
                <div className="project-photo">
                    <Image
                        src="/images/vr-wheelchair.jpg"
                        width="200"
                        height="200"
                    />
                </div>

                <p className={styles.description}>
                    VR Wheelchair is a wheelchair locomotion rig for virtual reality applications built in Unity.
                </p>
                <a href="https://github.com/justinmajetich/vr-wheelchair">Github Repository</a>
            </div>

            <div className="project">
                <h2>REST for the Wicked</h2>
                <div className="project-photo">
                    <Image
                        src="/images/rest-for-the-wicked.png"
                        width="200"
                        height="200"
                    />
                </div>

                <p className={styles.description}>
                REST for the Wicked is a text adventure game illustrating some of the basic concepts and interactions that define the REST framework.                </p>
                <a href="https://github.com/justinmajetich/rest-for-the-wicked">Github Repository</a>
                <a href="https://www.restforthewicked.app/">Project Website</a>
            </div>


        </div>
        <div className="nav-bar">
                <Link href="/"><a><h3>Home</h3></a></Link>
                <Link href="/about"><a><h3>About Me</h3></a></Link>
                <Link href="/resume"><a><h3>Resume</h3></a></Link>
                <Link href="/contact"><a><h3>Contact</h3></a></Link>
            </div>
    </main>

    <footer className={styles.footer}>
        <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
        >
        Powered by{' '}
        <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
        </a>
    </footer>
    </div>
)
}

export default Portfolio