import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

function Resume()
{
    return (
        <div className={styles.container}>
    <Head>
        <title>Justin Majetich</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
        <a href="/"><h1 className={styles.title}>
        Justin Majetich
        </h1></a>

        <h2>Resume</h2>

        <div className="resume"><Image
            src="/images/resume.png"
            width="576"
            height="746"
        /></div>
        <Link href="https://drive.google.com/uc?id=1MhHnNHhJvHDzx_naAs0UDFv1VWfvCItK&export=download"><a><h3>Download Resume</h3></a></Link>

        <div className="nav-bar">
            <Link href="/"><a><h3>Home</h3></a></Link>
            <Link href="/about"><a><h3>About Me</h3></a></Link>
            <Link href="/portfolio"><a><h3>Portfolio</h3></a></Link>
            <Link href="/contact"><a><h3>Contact</h3></a></Link>
        </div>

    </main>

    <footer className={styles.footer}>
        <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
        >
        Powered by{' '}
        <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
        </a>
    </footer>
    </div>
)
}

export default Resume